### ISSUE TITLE
Error in contrib.url(repos, type)

### ISSUE THREAD

**Issue by sk-sahu** [jimhester/azuretest#10]
I am trying to setup azure pipelines for a R package using this `r-azure-pipelines` but getting this following error. From what I understood its not able to fetch packages from CRAN and it requires `remotes` in Namespace. Is that correct??

My YML file - https://github.com/sk-sahu/sahu/blob/master/azure-pipelines.yml

[build pipeline](https://dev.azure.com/sahu-sk/r-sahu/_build/results?buildId=7&view=results)

Specific error in following:
```
Installing packages into ‘/__w/1/R/library’
(as ‘lib’ is unspecified)
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> grep -> contrib.url
Execution halted
Error in loadNamespace(name) : there is no package called ‘remotes’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
##[error]Bash exited with code '1'.

```

**Comment by sk-sahu** [comment]
Help please @jimhester

**Comment by jimhester** [comment]
You have a project specific `.Rprofile`, but you don't source the user level `.Rprofile`. I would suggest you don't use a project specific `.Rprofile`.
