### ISSUE TITLE
remove unneeded dependencies from old cache

### ISSUE THREAD

**Issue by maxheld83** [jimhester/azuretest#11]
Conceivably, commit `a` will include a dependency on R package *foo*, but a later commit `b` might remove that dependency from `DESCRIPTION`.
However, *foo* will still be in the cache, and may thus persist in the CI environment, until the cache is purged.

Not sure how pressing/likely this problem is, but perhaps it might lead to unexpected behaviours, bloat the cache and generally be hard to reason about.

I ran something like the below to fix this in GitHub Actions, though I'm not sure it's the most elegant way.

```
message("Checking for unneeded dependencies (might come from old cache) ...")
deps_exp <- remotes::dev_package_deps(dependencies = TRUE)$package
deps_present <- installed.packages()[, "Package"]
deps_uneeded <- setdiff(deps_present, deps_exp)
if (length(deps_uneeded > 0)) {
  remove.packages(deps_uneeded)
  message(
    "Removed one or more package dependencies no longer needed:",
    paste(deps_uneeded, collapse = ", ")
  )
}
```

Arguably this could be (or already is?) a feature or function in another package that could here simply be called (*remotes*?).

Would be happy to add a PR to `pkg-install_dependencies.yml`.

**Comment by jimhester** [comment]
The cache is invalidated when the DESCRIPTION changes, so this is not an issue.
