### ISSUE TITLE
Build and deploy binaries

### ISSUE THREAD

**Issue by jimhester** [jimhester/azuretest#2]
Shouldn't be a ton of work really, maybe can even make the artifacts into a CRAN-like repo directly?

**Comment by mtkerbeR** [comment]
Probably related to the issue above:
Based on the yaml-files (thanks a lot for your work on this, Jim), I was able to go a little step further and publish the resulting files/package 'testr' of the build pipeline as a "universal package" to an existing feed 'TestRFeed' in Azure DevOps Artifacts using the task **UniversalPackages@0** 

      - task: UniversalPackages@0
        displayName: Universal Publish
        inputs:
          command: publish
          publishDirectory: '$(System.DefaultWorkingDirectory)/R'
          vstsFeedPublish: 'TestRFeed'
          vstsFeedPackagePublish: 'testr'
          packagePublishDescription: 'A test package in R'

If this is any helpful, within the scope of the project and a small steps towards solving the issue, I would be happy to (try to) code this up as a template using variables for e.g. FeedName, PackageName and Package description.

However (according to my understand of the documentation in Azure DevOps), downloading/installing the package from the feed currently requires Azure CLI
[https://github.com/MicrosoftDocs/vsts-docs/issues/3834](https://github.com/MicrosoftDocs/vsts-docs/issues/3834)
This is in contrast to e.g. python packages, which can be installed locally from a python feed in Azure DevOps using pip.

Hence usefulness of the approach outlined above might be limited, at least for the time being ...
